# Generated by Django 2.1.5 on 2019-01-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_month', models.IntegerField()),
                ('fav_weekday', models.IntegerField()),
            ],
        ),
    ]
