# Generated by Django 2.1.5 on 2019-01-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='fav_month',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='fav_weekday',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
